SERVICE='https://YOUR_REDCAP_INSTALLATION/api/';
TOKEN='YOUR_API_TOKEN';

disp('************************');
disp('Download a file from a subject record');
disp('************************');
urlread(...
    SERVICE, ...
    'post', ...
    { 'token',   TOKEN,     ...
      'content', 'file',    ...
      'action',  'export',  ...
      'record',  'RECORD', ...
      'field',   'FIELD_NAME',    ...
    } ...
)
