SERVICE='https://YOUR_REDCAP_INSTALLATION/api/';
TOKEN='YOUR_API_TOKEN';

disp('************************');
disp('Import data in as flat csv');
disp('************************');
[reply, status] = urlread( ...
  SERVICE, 'post', ...
  {'token', TOKEN, ...
   'overwriteBehaviour', 'normal', ...
    'content', 'record', ...
    'format', 'csv', ...
    'type', 'flat' ...
    'data', fileread('FILE_TO_IMPORT') ...
  } ...
)

